config/routes.rb
Rails.application.routes.draw do
  resources :contexts
  resources :messages
  resources :resources
  resources :enrollments
  devise_for :users
  # root "landing#index"
  root "enrollments#new"

  resources :messages, only: [:new, :create]
  get 'landing/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/context.rb
class Context < ApplicationRecord
  has_many :enrollments, :dependent => :destroy
  has_many :resources, :dependent => :destroy
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  has_many :sent_messages, :class_name => "Message", :dependent => :destroy
  belongs_to :context
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :enrollment
  belongs_to :resource

  def username
    enrollment.user.email.gsub(/@.*/, "")
  end
end

app/models/resource.rb
class Resource < ApplicationRecord
  has_many :recieved_messages, :class_name => "Message", :dependent => :destroy
  belongs_to :context
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :enrollments, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contexts_controller.rb
class ContextsController < ApplicationController
  before_action :set_context, only: [:show, :edit, :update, :destroy]

  # GET /contexts
  def index
    @contexts = Context.all
  end

  # GET /contexts/1
  def show
  end

  # GET /contexts/new
  def new
    @context = Context.new
  end

  # GET /contexts/1/edit
  def edit
  end

  # POST /contexts
  def create
    @context = Context.new(context_params)

    if @context.save
      redirect_to @context, notice: 'Context was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /contexts/1
  def update
    if @context.update(context_params)
      redirect_to @context, notice: 'Context was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /contexts/1
  def destroy
    @context.destroy
    redirect_to contexts_url, notice: 'Context was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_context
      @context = Context.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def context_params
      params.require(:context).permit(:title, :id_from_tc)
    end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /enrollments
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  def create
    @enrollment = Enrollment.new(enrollment_params)

    if @enrollment.save
      redirect_to @enrollment, notice: 'Enrollment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /enrollments/1
  def update
    if @enrollment.update(enrollment_params)
      redirect_to @enrollment, notice: 'Enrollment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /enrollments/1
  def destroy
    @enrollment.destroy
    redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def enrollment_params
      params.require(:enrollment).permit(:user_id, :context_id)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  def index
    @messages = Message.all
  end

  # GET /messages/1
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  def create
    @message = Message.new(message_params)
    resource = @message.resource
    if @message.save
      # So this works as expected
      ResourceChannel.broadcast_to resource,
                     body: @message.body,
                     user: @message.enrollment.user.email 

      # ActionCable.server.broadcast resource,
      #                                   content: @message.body,
      #                                   user: @message.enrollment.user.email 
    else
      
    end
  end

  # PATCH/PUT /messages/1
  def update
    if @message.update(message_params)
      redirect_to @message, notice: 'Message was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /messages/1
  def destroy
    @message.destroy
    redirect_to messages_url, notice: 'Message was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def message_params
      params.require(:message).permit(:body, :enrollment_id, :resource_id)
    end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  # GET /resources
  def index
    @resources = Resource.all
  end

  # GET /resources/1
  def show
    @message = Message.new
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  def create
    @resource = Resource.new(resource_params)

    if @resource.save
      redirect_to @resource, notice: 'Resource was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /resources/1
  def update
    if @resource.update(resource_params)
      redirect_to @resource, notice: 'Resource was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /resources/1
  def destroy
    @resource.destroy
    redirect_to resources_url, notice: 'Resource was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def resource_params
      params.require(:resource).permit(:title, :id_from_tc, :context_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_show_or_back(object,
    show_content = "Show",
    back_content = "Back",
    options = {})
    if request.path == url_for(object)
      link_to back_content, :back, options
    else
      link_to show_content, object, options
    end
  end
end

app/helpers/contexts_helper.rb
module ContextsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/contexts/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Context #<%= context.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Title</dt>
      <dd><%= context.title %></dd>

      <dt>Id from tc</dt>
      <dd><%= context.id_from_tc %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back context, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_context_url(context), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to context, method: :delete, data: { confirm: "Do you really want to delete this context?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(context.updated_at) %> ago
  </div>
</div>

app/views/contexts/_form.html.erb
<% was_validated = context.errors.any? %>

<% form_html_options = { novalidate: true, class: "mb-3" } %>

<%= form_for(context, html: form_html_options) do |f| %>
  <div class="form-group">
    <% title_class = "form-control" %>
    <% title_was_invalid = context.errors.include?(:title) %>

    <% if was_validated %>
      <% if title_was_invalid %>
        <% title_class << " is-invalid" %>
      <% else %>
        <% title_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :title %>

    <%= f.text_field :title, class: title_class, placeholder: "Enter title" %>
    <% if title_was_invalid %>
      <% context.errors.full_messages_for(:title).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% id_from_tc_class = "form-control" %>
    <% id_from_tc_was_invalid = context.errors.include?(:id_from_tc) %>

    <% if was_validated %>
      <% if id_from_tc_was_invalid %>
        <% id_from_tc_class << " is-invalid" %>
      <% else %>
        <% id_from_tc_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :id_from_tc %>

    <%= f.text_field :id_from_tc, class: id_from_tc_class, placeholder: "Enter id from tc" %>
    <% if id_from_tc_was_invalid %>
      <% context.errors.full_messages_for(:id_from_tc).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/contexts/_list_item.html.erb
<%= link_to context, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    Context #<%= context.id %>

    <small class="text-muted">
      <%= time_ago_in_words(context.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/contexts/_table_row.html.erb
<tr>
  <td>
    <%= context.title %>
  </td>

  <td>
    <%= context.id_from_tc %>
  </td>

  <td>
    <div class="btn-group">
      <%= link_to context, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-search-plus fa-fw"></i>
      <% end %>

      <%= link_to edit_context_url(context), class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-edit fa-fw"></i>
      <% end %>

      <%= link_to context, method: :delete, data: { confirm: "Do you really want to delete this context?" }, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-trash-alt fa-fw"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/contexts/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Context #<%= @context.id %>
      </h2>

      <div class="card-body">
        <%= render "form", context: @context %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/contexts/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Contexts

      <%= link_to new_context_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<!-- Table example -->

<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>
              Title
            </th>

            <th>
              Id from tc
            </th>

            <th>
              Actions
            </th>
          </tr>
        </thead>

        <tbody>
          <%= render collection: @contexts, partial: "table_row", as: :context %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Card deck example -->

<% @contexts.each_slice(3) do |slice| %>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <%= render collection: slice, partial: "card", as: :context %>
    </div>
  </div>
</div>
<% end %>

<!-- List group example -->

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Contexts

        <%= link_to new_context_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @contexts, partial: "list_item", as: :context %>
      </div>
    </div>
  </div>
</div>

app/views/contexts/messages.html.erb
<div>
  <%= render collection: @resource.messages, partial: "table_row", as: :message %>
</div>

app/views/contexts/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Context
      </h2>

      <div class="card-body">
        <%= render "form", context: @context %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/contexts/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @context, partial: "card", as: :context %>
  </div>
</div>

app/views/enrollments/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Enrollment #<%= enrollment.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>User</dt>
      <dd><%= enrollment.user_id %></dd>

      <dt>Context</dt>
      <dd><%= enrollment.context_id %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back enrollment, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_enrollment_url(enrollment), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to enrollment, method: :delete, data: { confirm: "Do you really want to delete this enrollment?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(enrollment.updated_at) %> ago
  </div>
</div>

app/views/enrollments/_list_item.html.erb
<%= link_to enrollment, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    Enrollment #<%= enrollment.id %>

    <small class="text-muted">
      <%= time_ago_in_words(enrollment.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/enrollments/_table_row.html.erb
<tr>
  <td>
    <%= enrollment.user_id %>
  </td>

  <td>
    <%= enrollment.context_id %>
  </td>

  <td>
    <div class="btn-group">
      <%= link_to enrollment, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-search-plus fa-fw"></i>
      <% end %>

      <%= link_to edit_enrollment_url(enrollment), class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-edit fa-fw"></i>
      <% end %>

      <%= link_to enrollment, method: :delete, data: { confirm: "Do you really want to delete this enrollment?" }, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-trash-alt fa-fw"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/enrollments/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Enrollment #<%= @enrollment.id %>
      </h2>

      <div class="card-body">
        <%= render "form", enrollment: @enrollment %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/enrollments/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Enrollments

      <%= link_to new_enrollment_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<!-- Table example -->

<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>
              User
            </th>

            <th>
              Context
            </th>

            <th>
              Actions
            </th>
          </tr>
        </thead>

        <tbody>
          <%= render collection: @enrollments, partial: "table_row", as: :enrollment %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Card deck example -->

<% @enrollments.each_slice(3) do |slice| %>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <%= render collection: slice, partial: "card", as: :enrollment %>
    </div>
  </div>
</div>
<% end %>

<!-- List group example -->

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Enrollments

        <%= link_to new_enrollment_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @enrollments, partial: "list_item", as: :enrollment %>
      </div>
    </div>
  </div>
</div>

app/views/enrollments/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @enrollment, partial: "card", as: :enrollment %>
  </div>
</div>

app/views/messages/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Message #<%= message.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Body</dt>
      <dd><%= message.body %></dd>

      <dt>Enrollment</dt>
      <dd><%= message.enrollment_id %></dd>

      <dt>Resource</dt>
      <dd><%= message.resource_id %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back message, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_message_url(message), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to message, method: :delete, data: { confirm: "Do you really want to delete this message?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(message.updated_at) %> ago
  </div>
</div>

app/views/messages/_table_row.html.erb
<tr>
  <td>
    <%= message.body %>
  </td>

  <td>
    <%= message.enrollment_id %>
  </td>

  <td>
    <%= message.resource_id %>
  </td>

  <td>
    <div class="btn-group">
      <%= link_to message, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-search-plus fa-fw"></i>
      <% end %>

      <%= link_to edit_message_url(message), class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-edit fa-fw"></i>
      <% end %>

      <%= link_to message, method: :delete, data: { confirm: "Do you really want to delete this message?" }, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-trash-alt fa-fw"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/messages/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Messages

      <%= link_to new_message_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<!-- Table example -->

<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>
              Body
            </th>

            <th>
              Enrollment
            </th>

            <th>
              Resource
            </th>

            <th>
              Actions
            </th>
          </tr>
        </thead>

        <tbody>
          <%= render collection: @messages, partial: "table_row", as: :message %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Card deck example -->

<% @messages.each_slice(3) do |slice| %>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <%= render collection: slice, partial: "card", as: :message %>
    </div>
  </div>
</div>
<% end %>

<!-- List group example -->

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Messages

        <%= link_to new_message_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @messages, partial: "list_item", as: :message %>
      </div>
    </div>
  </div>
</div>

app/views/messages/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @message, partial: "card", as: :message %>
  </div>
</div>

app/views/resources/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Resource #<%= resource.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Title</dt>
      <dd><%= resource.title %></dd>

      <dt>Id from tc</dt>
      <dd><%= resource.id_from_tc %></dd>

      <dt>Context</dt>
      <dd><%= resource.context_id %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back resource, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_resource_url(resource), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to resource, method: :delete, data: { confirm: "Do you really want to delete this resource?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(resource.updated_at) %> ago
  </div>
</div>

app/views/resources/_table_row.html.erb
<tr>
  <td>
    <%= resource.title %>
  </td>

  <td>
    <%= resource.id_from_tc %>
  </td>

  <td>
    <%= resource.context_id %>
  </td>

  <td>
    <div class="btn-group">
      <%= link_to resource, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-search-plus fa-fw"></i>
      <% end %>

      <%= link_to edit_resource_url(resource), class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-edit fa-fw"></i>
      <% end %>

      <%= link_to resource, method: :delete, data: { confirm: "Do you really want to delete this resource?" }, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-trash-alt fa-fw"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/resources/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Resources

      <%= link_to new_resource_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<!-- Table example -->

<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>
              Title
            </th>

            <th>
              Id from tc
            </th>

            <th>
              Context
            </th>

            <th>
              Actions
            </th>
          </tr>
        </thead>

        <tbody>
          <%= render collection: @resources, partial: "table_row", as: :resource %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Card deck example -->

<% @resources.each_slice(3) do |slice| %>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <%= render collection: slice, partial: "card", as: :resource %>
    </div>
  </div>
</div>
<% end %>

<!-- List group example -->

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Resources

        <%= link_to new_resource_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @resources, partial: "list_item", as: :resource %>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>